Add YoloDetectedObject.msg and YoloDetectedObjects.msg
ichiro-its/ninshiki_interfaces pull request #6
Opened 2021-08-24 05:53 UTC by Nathan24zz

close #5.

2021-08-24 06:18 UTC, threeal requested changes
If there's compatibility problem, I suggest to define a general term for `DetectedObject` msg, and use it across multiple implementations (YOLO, TensorFlow, etc.). It's obvious to create a new msg because the old one is using index instead of string for the label, or because the coordinate is in integers instead of floating points.

2021-08-24 06:18 UTC, threeal commented on msg/YoloDetectedObject.msg
> +int32 y1
I suggest to change the `x0`, `y0`, `x1`, and `y1` into more descriptive name (e.g. `top`, `left`, `bottom`, and `right`).
Also, change the `YoloDetectedObject` name to be more general (e.g. `DetectedObject`, `BoxDetection`, etc.).

2021-08-24 06:18 UTC, threeal commented on msg/YoloDetectedObjects.msg
> +YoloDetectedObject[] detected_objects
Change this name to be more general too.

2021-08-24 13:09 UTC, threeal approved these changes
Looks good to me.

2021-08-24 13:14 UTC, threeal requested changes

2021-08-24 13:14 UTC, threeal commented on msg/DetectedObject.msg
> +int32 bottom
I think it's better to use floating point (`0`-`1`, represent position percentage on image) instead of integers for coordinate.

2021-08-25 04:26 UTC, threeal approved these changes
Looks good to me.

2021-08-27 03:15 UTC, maroqijalil approved these changes
LGTM

2021-08-27 03:15 UTC, merged